### ISSUE TITLE
Usage from command line

### ISSUE THREAD

**Issue by paulvi** [fhuberts/bndtoolsPlugins#4]
From http://marketplace.eclipse.org/content/bndtools-plugins-pelagic-stable one can understand that bndtoolsPlugins are extentions for bndtools. But as it mentions gradle plugin, it is not clear what this gradle plugin is capable, comparing to bdn gradle plugin (note that in bnd it is for workspace and non-workspace builds)

How to use from command line,  e.g. create headless build files ? Can this gradle plugin be used without bndtools, e.g. for non-workspace builds ?

please add in README

![](http://marketplace.eclipse.org/sites/default/files/styles/ds_solution_screenshot/public/Bndtools%20Plugins%20by%20Pelagic%20-%20Screenshot_0.png?itok=GRNa0mXt)

**Comment by fhuberts** [comment]
this is rather non-specific.
pls point to the location in the docs that are unclear

**Comment by paulvi** [comment]
> it is not clear what this gradle plugin is capable, comparing to bdn gradle plugin

**Comment by fhuberts** [comment]
See line 23 of https://github.com/fhuberts/bndtoolsPlugins/blob/master/nl.pelagic.bndtools.headless.build.plugin.gradle/resources/templates/unprocessed/cnf/gradle/doc/BUILDING-GRADLE.md

**Comment by paulvi** [comment]
That is good intro.
IMHO, this should be linked from README
